############################################################
# Dockerfile to build auto-magic DHuS container images
############################################################

FROM openjdk:8

MAINTAINER Andrea Tesseri - andrea.tesseri@gmail.com

# installing dep
RUN apt-get update && apt-get install -y \
zip \
curl \
vim
# installing DHuS
RUN mkdir logs
RUN curl -u xxx:xxx -o dhus-software-0.12.2-distribution.shar https://copernicus.serco.eu/repository/nexus/content/repositories/releases/fr/gael/dhus/dhus-software/0.12.2/dhus-software-0.12.2-distribution.shar
RUN chmod +x dhus-software-0.12.2-distribution.shar
RUN ./dhus-software-0.12.2-distribution.shar
# configuration
RUN sed -i -- 's/Xms12g/Xms512m/g; s/Xmx12g/Xmx512m/g' start.sh
RUN sed -i -- 's/local_dhus/\/local_dhus\/var/g; ' etc/dhus.xml
RUN sed -i '/Ddhus.scalability.active=true/ a -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=8081 -Dhttp.nonProxyHosts="127.0.0.*" -Djava.rmi.server.hostname=127.0.0.1 -Ddhus.scalability.local.protocol=http -Ddhus.scalability.local.port=8081 -Ddhus.scalability.local.path=/ \\' start.sh         

EXPOSE 8081

#ENTRYPOINT ["./start.sh" ]
#CMD ["127.0.0.1"]
CMD ["./start.sh"]
